---
version: "3.9"
services:
  b-svc:
    image: b-svc:dont_push
    container_name: b-svc
    hostname: b-svc
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - local_backend
    environment:
      - VIRTUAL_HOST=b-svc.local
      - VIRTUAL_PORT=8080
    expose:
      - "8080"  # spring boot HTTP port
      - "9999"  # xxl-job HTTP port
    command: >
        sh -c 'cp -pf /config/application.localdocker.yml /application.yml
        && java -jar /app.jar'
networks:
  local_backend:
    external: true
    name: local_backend
