---
version: "3.9"
services:
  java-springboot-svc:
    image: java-springboot-svc:dont_push
    container_name: java-springboot-svc
    hostname: java-springboot-svc
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - local
    environment:
      - VIRTUAL_HOST=java-springboot-svc.local
      - VIRTUAL_PORT=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector-0-86-0:4317
      - OTEL_RESOURCE_ATTRIBUTES-service.name=java-springboot-svc
    expose:
      - "8080"  # spring boot HTTP port
      - "9999"  # xxl-job HTTP port
    command: >
        sh -c 'cp -pf /config/application.localdocker.yml /application.yml
        && java --add-opens java.base/java.lang=ALL-UNNAMED -javaagent:/opentelemetry-javaagent.jar -jar /app.jar'
networks:
  local:
    external: true
    name: local
