---
version: "3.9"
services:
  java_springboot_svc:
    image: java_springboot_svc:dont_push
    container_name: java_springboot_svc
    hostname: java_springboot_svc
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - local_network
    environment:
      - VIRTUAL_HOST=java_springboot_svc.local
      - VIRTUAL_PORT=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES-service.name=java_springboot_svc
    expose:
      - "8080"  # spring boot HTTP port
      - "9999"  # xxl-job HTTP port
    command: >
        sh -c 'cp -pf /config/application.localdocker.yml /application.yml
        && java --add-opens java.base/java.lang=ALL-UNNAMED -javaagent:/opentelemetry-javaagent.jar -jar /app.jar'
networks:
  local_network:
    external: true
    name: local_network
