apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: java-springboot2-svc

resources:
  #- k8s-job-initdb.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  #- service-monitor.yaml
