server:
  servlet:
    encoding:
      charset: utf-8
      force-response: true

spring:
  application:
    name: java-springboot-svc  # used as fallback for tracing
  main:
    banner-mode: "off"
  datasource:
    # url: jdbc:postgresql://postgis-15-3-3:5432/java-springboot-svc?ssl=false
    # url: jdbc:mysql://127.0.0.1:3306/java-springboot-svc
    url: jdbc:mysql://mysql.db.svc:3306/java-springboot-svc  # for mysql deployed in k8s in "db" namespace
    username: java-springboot-svc
    password: java-springboot-svc
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false  # note: enabling this will mess up JSON log format
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect  # or org.hibernate.dialect.MySQL5Dialet
  sql:
    init:
      continue-on-error: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration  # Workaround for https://github.com/spring-projects/spring-boot/issues/16079

logging:
  level:  # TRACE/DEBUG/INFO/WARN/ERROR/FATAL/OFF - on production, all of them should be ERROR
    root: INFO
    org.springframework.web: INFO
    com.example.demo: DEBUG
    org.hibernate.SQL: DEBUG                  # print out hibernate generated SQL statements
    org.hibernate.type.descriptor.sql: TRACE  # to see the bounded values in the SQL query (recommended for development)
    org.hibernate.stat: DEBUG                 # to identify the most critical queries and prevent possible crashes in the prod environment
  # pattern:
    # console: "{\"t\":\"%date{ISO8601}\",\"l\":\"%level\",\"f\":\"%file\",\"ln\":\"%line\",\"m\":\"%msg\",\"thread\":\"%thread\"}%n"
mybatis:
  configuration:
    default-scripting-language: org.mybatis.scripting.thymeleaf.ThymeleafLanguageDriver  # Enable mybatis-thymeleaf feature

management:
  server.port: 8081
  endpoints.web.exposure.include: health,info,prometheus
  metrics.distribution.percentiles-histogram.http.server.requests: true
  tracing.sampling.probability: 1.0

xxl:
  job:
    admin:
      addresses: http://xxl-job-admin.xxl-job.svc:8080
    accessToken: default_token
    executor:
      appname: java-springboot-svc
      address: ""
      ip: ""
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
