apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: b-svc
  namespace: apps
spec:
  rules:
  - host: b-svc.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: b-svc
            port:
              number: 80
