apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-springboot-svc
  namespace: apps
spec:
  rules:
  - host: java-springboot-svc.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: java-springboot-svc
            port:
              number: 8080
