apiVersion: v1
kind: Service
metadata:
  name: java-springboot-svc
  namespace: apps
spec:
  selector:
    appID: java-springboot-svc
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
